// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package agentv1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/proto"
)

func AgentService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "agent.v1.AgentService", Name: "Health", Path: "/agent.v1.AgentService/Health", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListSessions", Path: "/agent.v1.AgentService/ListSessions", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "CreateSession", Path: "/agent.v1.AgentService/CreateSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetSession", Path: "/agent.v1.AgentService/GetSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeleteSession", Path: "/agent.v1.AgentService/DeleteSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListMessages", Path: "/agent.v1.AgentService/ListMessages", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Prompt", Path: "/agent.v1.AgentService/Prompt", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "WatchSession", Path: "/agent.v1.AgentService/WatchSession", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "WatchSessions", Path: "/agent.v1.AgentService/WatchSessions", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "Fork", Path: "/agent.v1.AgentService/Fork", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Rename", Path: "/agent.v1.AgentService/Rename", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetModel", Path: "/agent.v1.AgentService/SetModel", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Undo", Path: "/agent.v1.AgentService/Undo", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "State", Path: "/agent.v1.AgentService/State", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Mailbox", Path: "/agent.v1.AgentService/Mailbox", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UpdateSettings", Path: "/agent.v1.AgentService/UpdateSettings", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Interrupt", Path: "/agent.v1.AgentService/Interrupt", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Compact", Path: "/agent.v1.AgentService/Compact", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListProviders", Path: "/agent.v1.AgentService/ListProviders", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListProvidersCatalog", Path: "/agent.v1.AgentService/ListProvidersCatalog", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "RegisterProvider", Path: "/agent.v1.AgentService/RegisterProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeleteProvider", Path: "/agent.v1.AgentService/DeleteProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "TestProvider", Path: "/agent.v1.AgentService/TestProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListModels", Path: "/agent.v1.AgentService/ListModels", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListPresets", Path: "/agent.v1.AgentService/ListPresets", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UpsertPreset", Path: "/agent.v1.AgentService/UpsertPreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeletePreset", Path: "/agent.v1.AgentService/DeletePreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "PreviewPreset", Path: "/agent.v1.AgentService/PreviewPreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetConfig", Path: "/agent.v1.AgentService/GetConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetConfig", Path: "/agent.v1.AgentService/SetConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListTools", Path: "/agent.v1.AgentService/ListTools", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetToolConfig", Path: "/agent.v1.AgentService/GetToolConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetToolConfig", Path: "/agent.v1.AgentService/SetToolConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetExtensionConfig", Path: "/agent.v1.AgentService/SetExtensionConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UploadFile", Path: "/agent.v1.AgentService/UploadFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "IngestFile", Path: "/agent.v1.AgentService/IngestFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetFile", Path: "/agent.v1.AgentService/GetFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetFileMeta", Path: "/agent.v1.AgentService/GetFileMeta", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetAgentConfig", Path: "/agent.v1.AgentService/GetAgentConfig", ClientStream: false, ServerStream: false},
	}
}

type AgentServiceClient struct { rt easyrpc.Transport }
func NewAgentServiceClient(rt easyrpc.Transport) *AgentServiceClient { return &AgentServiceClient{rt: rt} }

func (c *AgentServiceClient) Health(ctx context.Context, in *HealthRequest) (*HealthResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Health", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &HealthResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest) (*ListSessionsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListSessions", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListSessionsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest) (*CreateSessionResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/CreateSession", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CreateSessionResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetSession", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetSessionResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeleteSession", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteSessionResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest) (*ListMessagesResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListMessages", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListMessagesResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Prompt(ctx context.Context, in *PromptRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Prompt", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *AgentServiceClient) WatchSession(ctx context.Context, in *WatchSessionRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/WatchSession", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *AgentServiceClient) WatchSessions(ctx context.Context, in *WatchSessionsRequest) (easyrpc.Stream, error) {
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/WatchSessions", Body: easyrpc.Frame(protoBytes(in), false)})
}

func (c *AgentServiceClient) Fork(ctx context.Context, in *ForkRequest) (*ForkResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Fork", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ForkResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Rename(ctx context.Context, in *RenameRequest) (*RenameResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Rename", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RenameResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetModel(ctx context.Context, in *SetModelRequest) (*SetModelResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetModel", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetModelResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Undo(ctx context.Context, in *UndoRequest) (*UndoResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Undo", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UndoResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) State(ctx context.Context, in *StateRequest) (*StateResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/State", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &StateResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Mailbox(ctx context.Context, in *MailboxRequest) (*MailboxResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Mailbox", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &MailboxResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest) (*UpdateSettingsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UpdateSettings", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpdateSettingsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Interrupt(ctx context.Context, in *InterruptRequest) (*InterruptResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Interrupt", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &InterruptResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Compact(ctx context.Context, in *CompactRequest) (*CompactResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Compact", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CompactResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest) (*ListProvidersResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListProviders", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListProvidersResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListProvidersCatalog(ctx context.Context, in *ListProvidersCatalogRequest) (*ListProvidersCatalogResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListProvidersCatalog", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListProvidersCatalogResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) RegisterProvider(ctx context.Context, in *RegisterProviderRequest) (*RegisterProviderResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/RegisterProvider", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RegisterProviderResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeleteProvider", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteProviderResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) TestProvider(ctx context.Context, in *TestProviderRequest) (*TestProviderResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/TestProvider", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &TestProviderResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListModels(ctx context.Context, in *ListModelsRequest) (*ListModelsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListModels", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListModelsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListPresets(ctx context.Context, in *ListPresetsRequest) (*ListPresetsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListPresets", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListPresetsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UpsertPreset(ctx context.Context, in *UpsertPresetRequest) (*UpsertPresetResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UpsertPreset", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpsertPresetResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeletePreset(ctx context.Context, in *DeletePresetRequest) (*DeletePresetResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeletePreset", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeletePresetResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) PreviewPreset(ctx context.Context, in *PreviewPresetRequest) (*PreviewPresetResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/PreviewPreset", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &PreviewPresetResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest) (*GetConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest) (*SetConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListTools", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListToolsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetToolConfig(ctx context.Context, in *GetToolConfigRequest) (*GetToolConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetToolConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetToolConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetToolConfig(ctx context.Context, in *SetToolConfigRequest) (*SetToolConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetToolConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetToolConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetExtensionConfig(ctx context.Context, in *SetExtensionConfigRequest) (*SetExtensionConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetExtensionConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetExtensionConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UploadFile", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UploadFileResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) IngestFile(ctx context.Context, in *IngestFileRequest) (*IngestFileResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/IngestFile", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IngestFileResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetFile", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetFileResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetFileMeta(ctx context.Context, in *GetFileMetaRequest) (*GetFileMetaResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetFileMeta", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetFileMetaResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest) (*GetAgentConfigResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetAgentConfig", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetAgentConfigResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

type AgentServiceService interface {
	Health(ctx context.Context, in *HealthRequest) (*HealthResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest) (*ListSessionsResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest) (*ListMessagesResponse, error)
	Prompt(ctx context.Context, in *PromptRequest, emit func(*PromptResponse) error) error
	WatchSession(ctx context.Context, in *WatchSessionRequest, emit func(*WatchSessionResponse) error) error
	WatchSessions(ctx context.Context, in *WatchSessionsRequest, emit func(*WatchSessionsResponse) error) error
	Fork(ctx context.Context, in *ForkRequest) (*ForkResponse, error)
	Rename(ctx context.Context, in *RenameRequest) (*RenameResponse, error)
	SetModel(ctx context.Context, in *SetModelRequest) (*SetModelResponse, error)
	Undo(ctx context.Context, in *UndoRequest) (*UndoResponse, error)
	State(ctx context.Context, in *StateRequest) (*StateResponse, error)
	Mailbox(ctx context.Context, in *MailboxRequest) (*MailboxResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest) (*UpdateSettingsResponse, error)
	Interrupt(ctx context.Context, in *InterruptRequest) (*InterruptResponse, error)
	Compact(ctx context.Context, in *CompactRequest) (*CompactResponse, error)
	ListProviders(ctx context.Context, in *ListProvidersRequest) (*ListProvidersResponse, error)
	ListProvidersCatalog(ctx context.Context, in *ListProvidersCatalogRequest) (*ListProvidersCatalogResponse, error)
	RegisterProvider(ctx context.Context, in *RegisterProviderRequest) (*RegisterProviderResponse, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest) (*DeleteProviderResponse, error)
	TestProvider(ctx context.Context, in *TestProviderRequest) (*TestProviderResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest) (*ListModelsResponse, error)
	ListPresets(ctx context.Context, in *ListPresetsRequest) (*ListPresetsResponse, error)
	UpsertPreset(ctx context.Context, in *UpsertPresetRequest) (*UpsertPresetResponse, error)
	DeletePreset(ctx context.Context, in *DeletePresetRequest) (*DeletePresetResponse, error)
	PreviewPreset(ctx context.Context, in *PreviewPresetRequest) (*PreviewPresetResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest) (*SetConfigResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error)
	GetToolConfig(ctx context.Context, in *GetToolConfigRequest) (*GetToolConfigResponse, error)
	SetToolConfig(ctx context.Context, in *SetToolConfigRequest) (*SetToolConfigResponse, error)
	SetExtensionConfig(ctx context.Context, in *SetExtensionConfigRequest) (*SetExtensionConfigResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error)
	IngestFile(ctx context.Context, in *IngestFileRequest) (*IngestFileResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error)
	GetFileMeta(ctx context.Context, in *GetFileMetaRequest) (*GetFileMetaResponse, error)
	GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest) (*GetAgentConfigResponse, error)
}

func RegisterAgentServiceService(impl AgentServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Health"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &HealthRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Health(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListSessions"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListSessionsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListSessions(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["CreateSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CreateSessionRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.CreateSession(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetSessionRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetSession(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["DeleteSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteSessionRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.DeleteSession(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListMessages"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListMessagesRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListMessages(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Stream["Prompt"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &PromptRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.Prompt(ctx, in, func(out *PromptResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Stream["WatchSession"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &WatchSessionRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.WatchSession(ctx, in, func(out *WatchSessionResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Stream["WatchSessions"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &WatchSessionsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return err }
		return impl.WatchSessions(ctx, in, func(out *WatchSessionsResponse) error { return emit(protoBytes(out), false) })
	}
	reg.Unary["Fork"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ForkRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Fork(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Rename"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RenameRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Rename(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["SetModel"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetModelRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.SetModel(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Undo"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UndoRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Undo(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["State"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &StateRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.State(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Mailbox"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &MailboxRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Mailbox(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["UpdateSettings"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpdateSettingsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.UpdateSettings(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Interrupt"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &InterruptRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Interrupt(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["Compact"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CompactRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.Compact(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListProviders"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListProvidersRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListProviders(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListProvidersCatalog"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListProvidersCatalogRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListProvidersCatalog(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["RegisterProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RegisterProviderRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.RegisterProvider(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["DeleteProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteProviderRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.DeleteProvider(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["TestProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &TestProviderRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.TestProvider(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListModels"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListModelsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListModels(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListPresets"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListPresetsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListPresets(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["UpsertPreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpsertPresetRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.UpsertPreset(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["DeletePreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeletePresetRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.DeletePreset(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["PreviewPreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &PreviewPresetRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.PreviewPreset(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["SetConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.SetConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListTools"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListToolsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListTools(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetToolConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetToolConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetToolConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["SetToolConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetToolConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.SetToolConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["SetExtensionConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetExtensionConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.SetExtensionConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["UploadFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UploadFileRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.UploadFile(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["IngestFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IngestFileRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.IngestFile(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetFileRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetFile(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetFileMeta"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetFileMetaRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetFileMeta(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["GetAgentConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetAgentConfigRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.GetAgentConfig(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	return reg
}

func AdminService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "agent.v1.AdminService", Name: "ListTenants", Path: "/agent.v1.AdminService/ListTenants", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "CreateTenant", Path: "/agent.v1.AdminService/CreateTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "UpdateTenant", Path: "/agent.v1.AdminService/UpdateTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "DeleteTenant", Path: "/agent.v1.AdminService/DeleteTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "IssueTenantToken", Path: "/agent.v1.AdminService/IssueTenantToken", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "ListTenantTokens", Path: "/agent.v1.AdminService/ListTenantTokens", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "RevokeTenantToken", Path: "/agent.v1.AdminService/RevokeTenantToken", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "RotateTenantToken", Path: "/agent.v1.AdminService/RotateTenantToken", ClientStream: false, ServerStream: false},
	}
}

type AdminServiceClient struct { rt easyrpc.Transport }
func NewAdminServiceClient(rt easyrpc.Transport) *AdminServiceClient { return &AdminServiceClient{rt: rt} }

func (c *AdminServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest) (*ListTenantsResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/ListTenants", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListTenantsResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest) (*CreateTenantResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/CreateTenant", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CreateTenantResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest) (*UpdateTenantResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/UpdateTenant", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpdateTenantResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/DeleteTenant", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteTenantResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) IssueTenantToken(ctx context.Context, in *IssueTenantTokenRequest) (*IssueTenantTokenResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/IssueTenantToken", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IssueTenantTokenResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) ListTenantTokens(ctx context.Context, in *ListTenantTokensRequest) (*ListTenantTokensResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/ListTenantTokens", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListTenantTokensResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) RevokeTenantToken(ctx context.Context, in *RevokeTenantTokenRequest) (*RevokeTenantTokenResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/RevokeTenantToken", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RevokeTenantTokenResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) RotateTenantToken(ctx context.Context, in *RotateTenantTokenRequest) (*RotateTenantTokenResponse, error) {
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/RotateTenantToken", Body: protoBytes(in)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RotateTenantTokenResponse{}
	if err := proto.Unmarshal(resp.Body, out); err != nil { return nil, err }
	return out, nil
}

type AdminServiceService interface {
	ListTenants(ctx context.Context, in *ListTenantsRequest) (*ListTenantsResponse, error)
	CreateTenant(ctx context.Context, in *CreateTenantRequest) (*CreateTenantResponse, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest) (*UpdateTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest) (*DeleteTenantResponse, error)
	IssueTenantToken(ctx context.Context, in *IssueTenantTokenRequest) (*IssueTenantTokenResponse, error)
	ListTenantTokens(ctx context.Context, in *ListTenantTokensRequest) (*ListTenantTokensResponse, error)
	RevokeTenantToken(ctx context.Context, in *RevokeTenantTokenRequest) (*RevokeTenantTokenResponse, error)
	RotateTenantToken(ctx context.Context, in *RotateTenantTokenRequest) (*RotateTenantTokenResponse, error)
}

func RegisterAdminServiceService(impl AdminServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["ListTenants"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListTenantsRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListTenants(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["CreateTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CreateTenantRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.CreateTenant(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["UpdateTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpdateTenantRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.UpdateTenant(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["DeleteTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteTenantRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.DeleteTenant(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["IssueTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IssueTenantTokenRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.IssueTenantToken(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["ListTenantTokens"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListTenantTokensRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.ListTenantTokens(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["RevokeTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RevokeTenantTokenRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.RevokeTenantToken(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	reg.Unary["RotateTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RotateTenantTokenRequest{}
		if err := proto.Unmarshal(req, in); err != nil { return nil, err }
		out, err := impl.RotateTenantToken(ctx, in)
		if err != nil { return nil, err }
		return protoBytes(out), nil
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

