// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package agentv1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

func AgentService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "agent.v1.AgentService", Name: "Health", Path: "/agent.v1.AgentService/Health", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetIdentity", Path: "/agent.v1.AgentService/GetIdentity", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListSessions", Path: "/agent.v1.AgentService/ListSessions", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "CreateSession", Path: "/agent.v1.AgentService/CreateSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetSession", Path: "/agent.v1.AgentService/GetSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeleteSession", Path: "/agent.v1.AgentService/DeleteSession", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListMessages", Path: "/agent.v1.AgentService/ListMessages", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Prompt", Path: "/agent.v1.AgentService/Prompt", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "WatchSession", Path: "/agent.v1.AgentService/WatchSession", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "WatchSessions", Path: "/agent.v1.AgentService/WatchSessions", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "Fork", Path: "/agent.v1.AgentService/Fork", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Rename", Path: "/agent.v1.AgentService/Rename", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetModel", Path: "/agent.v1.AgentService/SetModel", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Undo", Path: "/agent.v1.AgentService/Undo", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "State", Path: "/agent.v1.AgentService/State", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Mailbox", Path: "/agent.v1.AgentService/Mailbox", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UpdateSettings", Path: "/agent.v1.AgentService/UpdateSettings", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Interrupt", Path: "/agent.v1.AgentService/Interrupt", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "Compact", Path: "/agent.v1.AgentService/Compact", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListProviders", Path: "/agent.v1.AgentService/ListProviders", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListProvidersCatalog", Path: "/agent.v1.AgentService/ListProvidersCatalog", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "RegisterProvider", Path: "/agent.v1.AgentService/RegisterProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeleteProvider", Path: "/agent.v1.AgentService/DeleteProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "TestProvider", Path: "/agent.v1.AgentService/TestProvider", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListModels", Path: "/agent.v1.AgentService/ListModels", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListPresets", Path: "/agent.v1.AgentService/ListPresets", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UpsertPreset", Path: "/agent.v1.AgentService/UpsertPreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "DeletePreset", Path: "/agent.v1.AgentService/DeletePreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "PreviewPreset", Path: "/agent.v1.AgentService/PreviewPreset", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetConfig", Path: "/agent.v1.AgentService/GetConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetConfig", Path: "/agent.v1.AgentService/SetConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "ListTools", Path: "/agent.v1.AgentService/ListTools", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetToolConfig", Path: "/agent.v1.AgentService/GetToolConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetToolConfig", Path: "/agent.v1.AgentService/SetToolConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "SetExtensionConfig", Path: "/agent.v1.AgentService/SetExtensionConfig", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "UploadFile", Path: "/agent.v1.AgentService/UploadFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "IngestFile", Path: "/agent.v1.AgentService/IngestFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetFile", Path: "/agent.v1.AgentService/GetFile", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetFileMeta", Path: "/agent.v1.AgentService/GetFileMeta", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AgentService", Name: "GetFileStream", Path: "/agent.v1.AgentService/GetFileStream", ClientStream: false, ServerStream: true},
		{Service: "agent.v1.AgentService", Name: "GetAgentConfig", Path: "/agent.v1.AgentService/GetAgentConfig", ClientStream: false, ServerStream: false},
	}
}

type AgentServiceClient struct { rt easyrpc.Transport }
func NewAgentServiceClient(rt easyrpc.Transport) *AgentServiceClient { return &AgentServiceClient{rt: rt} }

func (c *AgentServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...easyrpc.CallOption) (*HealthResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Health", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &HealthResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...easyrpc.CallOption) (*GetIdentityResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetIdentity", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetIdentityResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...easyrpc.CallOption) (*ListSessionsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListSessions", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListSessionsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...easyrpc.CallOption) (*CreateSessionResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/CreateSession", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CreateSessionResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...easyrpc.CallOption) (*GetSessionResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetSession", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetSessionResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...easyrpc.CallOption) (*DeleteSessionResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeleteSession", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteSessionResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...easyrpc.CallOption) (*ListMessagesResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListMessages", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListMessagesResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Prompt(ctx context.Context, in *PromptRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Prompt", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *AgentServiceClient) WatchSession(ctx context.Context, in *WatchSessionRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/WatchSession", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *AgentServiceClient) WatchSessions(ctx context.Context, in *WatchSessionsRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/WatchSessions", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *AgentServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...easyrpc.CallOption) (*ForkResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Fork", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ForkResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...easyrpc.CallOption) (*RenameResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Rename", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RenameResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetModel(ctx context.Context, in *SetModelRequest, opts ...easyrpc.CallOption) (*SetModelResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetModel", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetModelResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Undo(ctx context.Context, in *UndoRequest, opts ...easyrpc.CallOption) (*UndoResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Undo", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UndoResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) State(ctx context.Context, in *StateRequest, opts ...easyrpc.CallOption) (*StateResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/State", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &StateResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Mailbox(ctx context.Context, in *MailboxRequest, opts ...easyrpc.CallOption) (*MailboxResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Mailbox", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &MailboxResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...easyrpc.CallOption) (*UpdateSettingsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UpdateSettings", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpdateSettingsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...easyrpc.CallOption) (*InterruptResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Interrupt", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &InterruptResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) Compact(ctx context.Context, in *CompactRequest, opts ...easyrpc.CallOption) (*CompactResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/Compact", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CompactResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...easyrpc.CallOption) (*ListProvidersResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListProviders", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListProvidersResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListProvidersCatalog(ctx context.Context, in *ListProvidersCatalogRequest, opts ...easyrpc.CallOption) (*ListProvidersCatalogResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListProvidersCatalog", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListProvidersCatalogResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) RegisterProvider(ctx context.Context, in *RegisterProviderRequest, opts ...easyrpc.CallOption) (*RegisterProviderResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/RegisterProvider", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RegisterProviderResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...easyrpc.CallOption) (*DeleteProviderResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeleteProvider", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteProviderResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) TestProvider(ctx context.Context, in *TestProviderRequest, opts ...easyrpc.CallOption) (*TestProviderResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/TestProvider", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &TestProviderResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...easyrpc.CallOption) (*ListModelsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListModels", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListModelsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListPresets(ctx context.Context, in *ListPresetsRequest, opts ...easyrpc.CallOption) (*ListPresetsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListPresets", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListPresetsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UpsertPreset(ctx context.Context, in *UpsertPresetRequest, opts ...easyrpc.CallOption) (*UpsertPresetResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UpsertPreset", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpsertPresetResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) DeletePreset(ctx context.Context, in *DeletePresetRequest, opts ...easyrpc.CallOption) (*DeletePresetResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/DeletePreset", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeletePresetResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) PreviewPreset(ctx context.Context, in *PreviewPresetRequest, opts ...easyrpc.CallOption) (*PreviewPresetResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/PreviewPreset", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &PreviewPresetResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...easyrpc.CallOption) (*GetConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...easyrpc.CallOption) (*SetConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...easyrpc.CallOption) (*ListToolsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/ListTools", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListToolsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetToolConfig(ctx context.Context, in *GetToolConfigRequest, opts ...easyrpc.CallOption) (*GetToolConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetToolConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetToolConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetToolConfig(ctx context.Context, in *SetToolConfigRequest, opts ...easyrpc.CallOption) (*SetToolConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetToolConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetToolConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) SetExtensionConfig(ctx context.Context, in *SetExtensionConfigRequest, opts ...easyrpc.CallOption) (*SetExtensionConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/SetExtensionConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &SetExtensionConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...easyrpc.CallOption) (*UploadFileResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/UploadFile", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UploadFileResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) IngestFile(ctx context.Context, in *IngestFileRequest, opts ...easyrpc.CallOption) (*IngestFileResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/IngestFile", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IngestFileResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...easyrpc.CallOption) (*GetFileResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetFile", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetFileResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...easyrpc.CallOption) (*GetFileMetaResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetFileMeta", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetFileMetaResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AgentServiceClient) GetFileStream(ctx context.Context, in *GetFileRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetFileStream", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *AgentServiceClient) GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest, opts ...easyrpc.CallOption) (*GetAgentConfigResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AgentService/GetAgentConfig", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetAgentConfigResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

type AgentServiceService interface {
	Health(ctx context.Context, in *HealthRequest) (*HealthResponse, error)
	GetIdentity(ctx context.Context, in *GetIdentityRequest) (*GetIdentityResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest) (*ListSessionsResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest) (*ListMessagesResponse, error)
	Prompt(ctx context.Context, in *PromptRequest, emit func(*PromptResponse) error) error
	WatchSession(ctx context.Context, in *WatchSessionRequest, emit func(*WatchSessionResponse) error) error
	WatchSessions(ctx context.Context, in *WatchSessionsRequest, emit func(*WatchSessionsResponse) error) error
	Fork(ctx context.Context, in *ForkRequest) (*ForkResponse, error)
	Rename(ctx context.Context, in *RenameRequest) (*RenameResponse, error)
	SetModel(ctx context.Context, in *SetModelRequest) (*SetModelResponse, error)
	Undo(ctx context.Context, in *UndoRequest) (*UndoResponse, error)
	State(ctx context.Context, in *StateRequest) (*StateResponse, error)
	Mailbox(ctx context.Context, in *MailboxRequest) (*MailboxResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest) (*UpdateSettingsResponse, error)
	Interrupt(ctx context.Context, in *InterruptRequest) (*InterruptResponse, error)
	Compact(ctx context.Context, in *CompactRequest) (*CompactResponse, error)
	ListProviders(ctx context.Context, in *ListProvidersRequest) (*ListProvidersResponse, error)
	ListProvidersCatalog(ctx context.Context, in *ListProvidersCatalogRequest) (*ListProvidersCatalogResponse, error)
	RegisterProvider(ctx context.Context, in *RegisterProviderRequest) (*RegisterProviderResponse, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest) (*DeleteProviderResponse, error)
	TestProvider(ctx context.Context, in *TestProviderRequest) (*TestProviderResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest) (*ListModelsResponse, error)
	ListPresets(ctx context.Context, in *ListPresetsRequest) (*ListPresetsResponse, error)
	UpsertPreset(ctx context.Context, in *UpsertPresetRequest) (*UpsertPresetResponse, error)
	DeletePreset(ctx context.Context, in *DeletePresetRequest) (*DeletePresetResponse, error)
	PreviewPreset(ctx context.Context, in *PreviewPresetRequest) (*PreviewPresetResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest) (*SetConfigResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error)
	GetToolConfig(ctx context.Context, in *GetToolConfigRequest) (*GetToolConfigResponse, error)
	SetToolConfig(ctx context.Context, in *SetToolConfigRequest) (*SetToolConfigResponse, error)
	SetExtensionConfig(ctx context.Context, in *SetExtensionConfigRequest) (*SetExtensionConfigResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error)
	IngestFile(ctx context.Context, in *IngestFileRequest) (*IngestFileResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error)
	GetFileMeta(ctx context.Context, in *GetFileMetaRequest) (*GetFileMetaResponse, error)
	GetFileStream(ctx context.Context, in *GetFileRequest, emit func(*FileChunk) error) error
	GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest) (*GetAgentConfigResponse, error)
}

func RegisterAgentServiceService(impl AgentServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Health"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &HealthRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Health(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetIdentity"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetIdentityRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetIdentity(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListSessions"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListSessionsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListSessions(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["CreateSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CreateSessionRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.CreateSession(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetSessionRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetSession(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["DeleteSession"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteSessionRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.DeleteSession(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListMessages"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListMessagesRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListMessages(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Stream["Prompt"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &PromptRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.Prompt(ctx, in, func(out *PromptResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Stream["WatchSession"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &WatchSessionRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.WatchSession(ctx, in, func(out *WatchSessionResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Stream["WatchSessions"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &WatchSessionsRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.WatchSessions(ctx, in, func(out *WatchSessionsResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Unary["Fork"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ForkRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Fork(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["Rename"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RenameRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Rename(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["SetModel"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetModelRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.SetModel(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["Undo"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UndoRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Undo(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["State"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &StateRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.State(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["Mailbox"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &MailboxRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Mailbox(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["UpdateSettings"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpdateSettingsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.UpdateSettings(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["Interrupt"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &InterruptRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Interrupt(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["Compact"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CompactRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Compact(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListProviders"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListProvidersRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListProviders(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListProvidersCatalog"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListProvidersCatalogRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListProvidersCatalog(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["RegisterProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RegisterProviderRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.RegisterProvider(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["DeleteProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteProviderRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.DeleteProvider(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["TestProvider"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &TestProviderRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.TestProvider(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListModels"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListModelsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListModels(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListPresets"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListPresetsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListPresets(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["UpsertPreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpsertPresetRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.UpsertPreset(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["DeletePreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeletePresetRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.DeletePreset(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["PreviewPreset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &PreviewPresetRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.PreviewPreset(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["SetConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.SetConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListTools"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListToolsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListTools(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetToolConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetToolConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetToolConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["SetToolConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetToolConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.SetToolConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["SetExtensionConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &SetExtensionConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.SetExtensionConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["UploadFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UploadFileRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.UploadFile(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["IngestFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IngestFileRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.IngestFile(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetFile"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetFileRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetFile(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["GetFileMeta"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetFileMetaRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetFileMeta(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Stream["GetFileStream"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &GetFileRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.GetFileStream(ctx, in, func(out *FileChunk) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Unary["GetAgentConfig"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetAgentConfigRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetAgentConfig(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	return reg
}

func AdminService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "agent.v1.AdminService", Name: "ListTenants", Path: "/agent.v1.AdminService/ListTenants", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "CreateTenant", Path: "/agent.v1.AdminService/CreateTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "UpdateTenant", Path: "/agent.v1.AdminService/UpdateTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "DeleteTenant", Path: "/agent.v1.AdminService/DeleteTenant", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "IssueTenantToken", Path: "/agent.v1.AdminService/IssueTenantToken", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "ListTenantTokens", Path: "/agent.v1.AdminService/ListTenantTokens", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "RevokeTenantToken", Path: "/agent.v1.AdminService/RevokeTenantToken", ClientStream: false, ServerStream: false},
		{Service: "agent.v1.AdminService", Name: "RotateTenantToken", Path: "/agent.v1.AdminService/RotateTenantToken", ClientStream: false, ServerStream: false},
	}
}

type AdminServiceClient struct { rt easyrpc.Transport }
func NewAdminServiceClient(rt easyrpc.Transport) *AdminServiceClient { return &AdminServiceClient{rt: rt} }

func (c *AdminServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...easyrpc.CallOption) (*ListTenantsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/ListTenants", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListTenantsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...easyrpc.CallOption) (*CreateTenantResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/CreateTenant", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &CreateTenantResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...easyrpc.CallOption) (*UpdateTenantResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/UpdateTenant", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &UpdateTenantResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...easyrpc.CallOption) (*DeleteTenantResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/DeleteTenant", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &DeleteTenantResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) IssueTenantToken(ctx context.Context, in *IssueTenantTokenRequest, opts ...easyrpc.CallOption) (*IssueTenantTokenResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/IssueTenantToken", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &IssueTenantTokenResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) ListTenantTokens(ctx context.Context, in *ListTenantTokensRequest, opts ...easyrpc.CallOption) (*ListTenantTokensResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/ListTenantTokens", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListTenantTokensResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) RevokeTenantToken(ctx context.Context, in *RevokeTenantTokenRequest, opts ...easyrpc.CallOption) (*RevokeTenantTokenResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/RevokeTenantToken", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RevokeTenantTokenResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *AdminServiceClient) RotateTenantToken(ctx context.Context, in *RotateTenantTokenRequest, opts ...easyrpc.CallOption) (*RotateTenantTokenResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/agent.v1.AdminService/RotateTenantToken", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &RotateTenantTokenResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

type AdminServiceService interface {
	ListTenants(ctx context.Context, in *ListTenantsRequest) (*ListTenantsResponse, error)
	CreateTenant(ctx context.Context, in *CreateTenantRequest) (*CreateTenantResponse, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest) (*UpdateTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest) (*DeleteTenantResponse, error)
	IssueTenantToken(ctx context.Context, in *IssueTenantTokenRequest) (*IssueTenantTokenResponse, error)
	ListTenantTokens(ctx context.Context, in *ListTenantTokensRequest) (*ListTenantTokensResponse, error)
	RevokeTenantToken(ctx context.Context, in *RevokeTenantTokenRequest) (*RevokeTenantTokenResponse, error)
	RotateTenantToken(ctx context.Context, in *RotateTenantTokenRequest) (*RotateTenantTokenResponse, error)
}

func RegisterAdminServiceService(impl AdminServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["ListTenants"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListTenantsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListTenants(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["CreateTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &CreateTenantRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.CreateTenant(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["UpdateTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &UpdateTenantRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.UpdateTenant(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["DeleteTenant"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &DeleteTenantRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.DeleteTenant(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["IssueTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &IssueTenantTokenRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.IssueTenantToken(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListTenantTokens"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListTenantTokensRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListTenantTokens(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["RevokeTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RevokeTenantTokenRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.RevokeTenantToken(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["RotateTenantToken"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &RotateTenantTokenRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.RotateTenantToken(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

func encodeMsg(m proto.Message, kind easyrpc.ContentKind) []byte {
	if kind == easyrpc.KindJSON {
		b, err := protojson.Marshal(m)
		if err != nil {
			return []byte("{}")
		}
		return b
	}
	return protoBytes(m)
}

func decodeMsg(b []byte, m proto.Message, kind easyrpc.ContentKind) error {
	if kind == easyrpc.KindJSON {
		return protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(b, m)
	}
	return proto.Unmarshal(b, m)
}
